# Site settings
title: Company Reputation Tracker
description: Track company mentions and sentiment analysis


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
remote_theme: pages-themes/minima@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - .github/
  - __pycache__/
  - api_client.py
  - company_tracker.db
  - dashboard.py
  - db.py
  - logger.py
  - logs/
  - requirements.txt
  - runner.py
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/