name: Company Reputation Tracker

on:
  schedule:
    - cron: '30 17 * * *'  # 5:30 PM UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  # First job: Update data and commit changes
  update_data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nltk
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
      
      - name: Run data processing pipeline
        run: |
          # Initialize DB and directories
          mkdir -p logs assets/data
          python -c "from db import init_db; init_db()"
          
          # Process data and generate static files
          python runner.py --all --limit 20 || python runner.py --generate-only
          python generate_static_data.py
          
          # Verify files were generated
          if [ -f "assets/data/dashboard_data.json" ]; then
            echo "✅ Static data generated successfully"
          else
            echo "❌ Failed to generate static data"
            exit 1
          fi
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add assets/data/*.json company_tracker.db logs/*.log || true
          git diff --staged --quiet || git commit -m "Update dashboard data [skip ci]"
          git push || echo "No changes to push or push failed"

  # Second job: Deploy to GitHub Pages
  deploy_pages:
    needs: update_data
    runs-on: ubuntu-latest
    
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
