name: Daily Company Reputation Tracker

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  track_reputation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run reputation tracker
        run: |
          python runner.py
      
      - name: Generate static data files
        run: |
          python generate_static_data.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain assets/data/
          if [[ $(git status --porcelain assets/data/) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/data/*.json
          git commit -m "Update dashboard data [skip ci]"
          git push
