name: Daily Company Reputation Tracker

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '20 17 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  track_reputation:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
      
      - name: Check API keys
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Warning: OPENAI_API_KEY is not set. Sentiment analysis may not work properly."
          fi
          if [ -z "$NEWSAPI_KEY" ]; then
            echo "Warning: NEWSAPI_KEY is not set. News fetching may not work properly."
          fi
      
      - name: Run reputation tracker
        run: |
          python runner.py
      
      - name: Generate static data files
        run: |
          python generate_static_data.py
      
      - name: Verify data files were generated
        run: |
          if [ -f "assets/data/dashboard_data.json" ] && [ -f "assets/data/companies.json" ]; then
            echo "Data files successfully generated"
          else
            echo "Warning: Some data files are missing"
            ls -la assets/data/
          fi
      
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain assets/data/
          if [[ $(git status --porcelain assets/data/) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/data/*.json
          git commit -m "Update dashboard data [skip ci]"
          git push
      
      - name: Upload data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dashboard-data
          path: assets/data/*.json
          retention-days: 7
