name: Daily Company Reputation Tracker

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-mentions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import nltk; nltk.download('punkt'); nltk.download('averaged_perceptron_tagger')"
      
      - name: Fetch and analyze company mentions
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: python runner.py --all
      
      - name: Upload database as artifact
        uses: actions/upload-artifact@v3
        with:
          name: company-tracker-db
          path: company_tracker.db
          retention-days: 7
      
      - name: Upload run report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-run-report
          path: pipeline_run_report.json
          retention-days: 7
      
      # Optional: Push database changes back to the repository
      - name: Push database changes to repository
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add company_tracker.db
          git commit -m "Update company mentions database [skip ci]" || echo "No changes to commit"
          git push